// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: trashandcashblockchain/trashandcashblockchain/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgBankReplenishment struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Amount  string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *MsgBankReplenishment) Reset()         { *m = MsgBankReplenishment{} }
func (m *MsgBankReplenishment) String() string { return proto.CompactTextString(m) }
func (*MsgBankReplenishment) ProtoMessage()    {}
func (*MsgBankReplenishment) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b0342a5fcd38970, []int{0}
}
func (m *MsgBankReplenishment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBankReplenishment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBankReplenishment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBankReplenishment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBankReplenishment.Merge(m, src)
}
func (m *MsgBankReplenishment) XXX_Size() int {
	return m.Size()
}
func (m *MsgBankReplenishment) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBankReplenishment.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBankReplenishment proto.InternalMessageInfo

func (m *MsgBankReplenishment) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgBankReplenishment) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type MsgBankReplenishmentResponse struct {
}

func (m *MsgBankReplenishmentResponse) Reset()         { *m = MsgBankReplenishmentResponse{} }
func (m *MsgBankReplenishmentResponse) String() string { return proto.CompactTextString(m) }
func (*MsgBankReplenishmentResponse) ProtoMessage()    {}
func (*MsgBankReplenishmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b0342a5fcd38970, []int{1}
}
func (m *MsgBankReplenishmentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBankReplenishmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBankReplenishmentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBankReplenishmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBankReplenishmentResponse.Merge(m, src)
}
func (m *MsgBankReplenishmentResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgBankReplenishmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBankReplenishmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBankReplenishmentResponse proto.InternalMessageInfo

type MsgWithdrawBank struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Amount  string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *MsgWithdrawBank) Reset()         { *m = MsgWithdrawBank{} }
func (m *MsgWithdrawBank) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawBank) ProtoMessage()    {}
func (*MsgWithdrawBank) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b0342a5fcd38970, []int{2}
}
func (m *MsgWithdrawBank) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdrawBank) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdrawBank.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdrawBank) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawBank.Merge(m, src)
}
func (m *MsgWithdrawBank) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdrawBank) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawBank.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawBank proto.InternalMessageInfo

func (m *MsgWithdrawBank) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgWithdrawBank) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type MsgWithdrawBankResponse struct {
}

func (m *MsgWithdrawBankResponse) Reset()         { *m = MsgWithdrawBankResponse{} }
func (m *MsgWithdrawBankResponse) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawBankResponse) ProtoMessage()    {}
func (*MsgWithdrawBankResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b0342a5fcd38970, []int{3}
}
func (m *MsgWithdrawBankResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdrawBankResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdrawBankResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdrawBankResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawBankResponse.Merge(m, src)
}
func (m *MsgWithdrawBankResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdrawBankResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawBankResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawBankResponse proto.InternalMessageInfo

type MsgSpinReels struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Amount  string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *MsgSpinReels) Reset()         { *m = MsgSpinReels{} }
func (m *MsgSpinReels) String() string { return proto.CompactTextString(m) }
func (*MsgSpinReels) ProtoMessage()    {}
func (*MsgSpinReels) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b0342a5fcd38970, []int{4}
}
func (m *MsgSpinReels) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSpinReels) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSpinReels.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSpinReels) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSpinReels.Merge(m, src)
}
func (m *MsgSpinReels) XXX_Size() int {
	return m.Size()
}
func (m *MsgSpinReels) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSpinReels.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSpinReels proto.InternalMessageInfo

func (m *MsgSpinReels) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSpinReels) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type MsgSpinReelsResponse struct {
	Id      uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Bet     string `protobuf:"bytes,2,opt,name=bet,proto3" json:"bet,omitempty"`
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Result  string `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	Winning string `protobuf:"bytes,5,opt,name=winning,proto3" json:"winning,omitempty"`
}

func (m *MsgSpinReelsResponse) Reset()         { *m = MsgSpinReelsResponse{} }
func (m *MsgSpinReelsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSpinReelsResponse) ProtoMessage()    {}
func (*MsgSpinReelsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b0342a5fcd38970, []int{5}
}
func (m *MsgSpinReelsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSpinReelsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSpinReelsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSpinReelsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSpinReelsResponse.Merge(m, src)
}
func (m *MsgSpinReelsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSpinReelsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSpinReelsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSpinReelsResponse proto.InternalMessageInfo

func (m *MsgSpinReelsResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgSpinReelsResponse) GetBet() string {
	if m != nil {
		return m.Bet
	}
	return ""
}

func (m *MsgSpinReelsResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MsgSpinReelsResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *MsgSpinReelsResponse) GetWinning() string {
	if m != nil {
		return m.Winning
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgBankReplenishment)(nil), "trashandcashblockchain.trashandcashblockchain.MsgBankReplenishment")
	proto.RegisterType((*MsgBankReplenishmentResponse)(nil), "trashandcashblockchain.trashandcashblockchain.MsgBankReplenishmentResponse")
	proto.RegisterType((*MsgWithdrawBank)(nil), "trashandcashblockchain.trashandcashblockchain.MsgWithdrawBank")
	proto.RegisterType((*MsgWithdrawBankResponse)(nil), "trashandcashblockchain.trashandcashblockchain.MsgWithdrawBankResponse")
	proto.RegisterType((*MsgSpinReels)(nil), "trashandcashblockchain.trashandcashblockchain.MsgSpinReels")
	proto.RegisterType((*MsgSpinReelsResponse)(nil), "trashandcashblockchain.trashandcashblockchain.MsgSpinReelsResponse")
}

func init() {
	proto.RegisterFile("trashandcashblockchain/trashandcashblockchain/tx.proto", fileDescriptor_9b0342a5fcd38970)
}

var fileDescriptor_9b0342a5fcd38970 = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x3f, 0x4b, 0xc3, 0x40,
	0x18, 0xc6, 0x7b, 0x4d, 0xad, 0xf4, 0xa5, 0xf8, 0x27, 0x88, 0xc6, 0x22, 0x41, 0x3a, 0xb9, 0x34,
	0x82, 0x82, 0x8b, 0x20, 0xd2, 0x82, 0x08, 0x12, 0x90, 0x38, 0x08, 0x6e, 0xd7, 0xe4, 0x48, 0x8e,
	0xa6, 0x97, 0x90, 0x37, 0xa5, 0x75, 0x77, 0x15, 0x9c, 0xfc, 0x06, 0x7e, 0x17, 0xc7, 0x4e, 0xe2,
	0x28, 0xed, 0x17, 0x91, 0x24, 0x4d, 0x6c, 0x35, 0x1d, 0xda, 0xba, 0xe5, 0xb9, 0xdc, 0xf3, 0x7b,
	0x8e, 0x7b, 0xef, 0x81, 0xb3, 0x30, 0xa0, 0xe8, 0x50, 0x61, 0x99, 0x14, 0x9d, 0xb6, 0xeb, 0x99,
	0x1d, 0xd3, 0xa1, 0x5c, 0x1c, 0xcf, 0x5b, 0x1e, 0x68, 0x7e, 0xe0, 0x85, 0x9e, 0xdc, 0xc8, 0xdf,
	0xa0, 0xe5, 0x2f, 0xd7, 0xaf, 0x61, 0x47, 0x47, 0xbb, 0x49, 0x45, 0xc7, 0x60, 0xbe, 0xcb, 0x04,
	0x47, 0xa7, 0xcb, 0x44, 0x28, 0x2b, 0xb0, 0x6e, 0x06, 0x8c, 0x86, 0x5e, 0xa0, 0x90, 0x43, 0x72,
	0x54, 0x31, 0x52, 0x29, 0xef, 0x42, 0x99, 0x76, 0xbd, 0x9e, 0x08, 0x95, 0x62, 0xfc, 0x63, 0xa2,
	0xea, 0x2a, 0x1c, 0xe4, 0x91, 0x0c, 0x86, 0xbe, 0x27, 0x90, 0xd5, 0x5b, 0xb0, 0xa9, 0xa3, 0x7d,
	0xcf, 0x43, 0xc7, 0x0a, 0x68, 0x3f, 0xda, 0xb7, 0x44, 0xc8, 0x3e, 0xec, 0xfd, 0x82, 0x64, 0xfc,
	0x4b, 0xa8, 0xea, 0x68, 0xdf, 0xf9, 0x5c, 0x18, 0x8c, 0xb9, 0xb8, 0x04, 0xfc, 0x89, 0xc4, 0x97,
	0x91, 0x21, 0x52, 0xb4, 0xbc, 0x01, 0x45, 0x6e, 0xc5, 0x94, 0x92, 0x51, 0xe4, 0x96, 0xbc, 0x05,
	0x52, 0x9b, 0xa5, 0xee, 0xe8, 0x33, 0x0a, 0xa3, 0x96, 0x15, 0x30, 0x44, 0x45, 0x4a, 0xc2, 0x26,
	0x32, 0x0a, 0x0b, 0x18, 0xf6, 0xdc, 0x50, 0x29, 0x25, 0x61, 0x89, 0x8a, 0x1c, 0x7d, 0x2e, 0x04,
	0x17, 0xb6, 0xb2, 0x96, 0x38, 0x26, 0xf2, 0xe4, 0x43, 0x02, 0x49, 0x47, 0x5b, 0x7e, 0x23, 0xb0,
	0xfd, 0x77, 0x30, 0x2d, 0x6d, 0xa1, 0x01, 0x6b, 0x79, 0x33, 0xa9, 0xdd, 0xfc, 0x03, 0x24, 0xbb,
	0x9d, 0x57, 0x02, 0xd5, 0x99, 0xb1, 0x5e, 0x2c, 0x4e, 0x9f, 0xf6, 0xd7, 0xae, 0x56, 0xf3, 0x67,
	0x07, 0x7b, 0x26, 0x50, 0xf9, 0x79, 0x0f, 0xe7, 0x8b, 0x53, 0x33, 0x73, 0xad, 0xb5, 0x82, 0x39,
	0x3d, 0x4f, 0xf3, 0xf6, 0x7d, 0xa4, 0x92, 0xe1, 0x48, 0x25, 0x5f, 0x23, 0x95, 0xbc, 0x8c, 0xd5,
	0xc2, 0x70, 0xac, 0x16, 0x3e, 0xc7, 0x6a, 0xe1, 0x61, 0xa6, 0xec, 0x8d, 0xa9, 0x5a, 0x0f, 0xe6,
	0xf6, 0xfd, 0xd1, 0x67, 0xd8, 0x2e, 0xc7, 0x9d, 0x3f, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x95,
	0xbd, 0x30, 0x41, 0x2d, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	BankReplenishment(ctx context.Context, in *MsgBankReplenishment, opts ...grpc.CallOption) (*MsgBankReplenishmentResponse, error)
	WithdrawBank(ctx context.Context, in *MsgWithdrawBank, opts ...grpc.CallOption) (*MsgWithdrawBankResponse, error)
	SpinReels(ctx context.Context, in *MsgSpinReels, opts ...grpc.CallOption) (*MsgSpinReelsResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) BankReplenishment(ctx context.Context, in *MsgBankReplenishment, opts ...grpc.CallOption) (*MsgBankReplenishmentResponse, error) {
	out := new(MsgBankReplenishmentResponse)
	err := c.cc.Invoke(ctx, "/trashandcashblockchain.trashandcashblockchain.Msg/BankReplenishment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) WithdrawBank(ctx context.Context, in *MsgWithdrawBank, opts ...grpc.CallOption) (*MsgWithdrawBankResponse, error) {
	out := new(MsgWithdrawBankResponse)
	err := c.cc.Invoke(ctx, "/trashandcashblockchain.trashandcashblockchain.Msg/WithdrawBank", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SpinReels(ctx context.Context, in *MsgSpinReels, opts ...grpc.CallOption) (*MsgSpinReelsResponse, error) {
	out := new(MsgSpinReelsResponse)
	err := c.cc.Invoke(ctx, "/trashandcashblockchain.trashandcashblockchain.Msg/SpinReels", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	BankReplenishment(context.Context, *MsgBankReplenishment) (*MsgBankReplenishmentResponse, error)
	WithdrawBank(context.Context, *MsgWithdrawBank) (*MsgWithdrawBankResponse, error)
	SpinReels(context.Context, *MsgSpinReels) (*MsgSpinReelsResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) BankReplenishment(ctx context.Context, req *MsgBankReplenishment) (*MsgBankReplenishmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BankReplenishment not implemented")
}
func (*UnimplementedMsgServer) WithdrawBank(ctx context.Context, req *MsgWithdrawBank) (*MsgWithdrawBankResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawBank not implemented")
}
func (*UnimplementedMsgServer) SpinReels(ctx context.Context, req *MsgSpinReels) (*MsgSpinReelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpinReels not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_BankReplenishment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBankReplenishment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).BankReplenishment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trashandcashblockchain.trashandcashblockchain.Msg/BankReplenishment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).BankReplenishment(ctx, req.(*MsgBankReplenishment))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_WithdrawBank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgWithdrawBank)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).WithdrawBank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trashandcashblockchain.trashandcashblockchain.Msg/WithdrawBank",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).WithdrawBank(ctx, req.(*MsgWithdrawBank))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SpinReels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSpinReels)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SpinReels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trashandcashblockchain.trashandcashblockchain.Msg/SpinReels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SpinReels(ctx, req.(*MsgSpinReels))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "trashandcashblockchain.trashandcashblockchain.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BankReplenishment",
			Handler:    _Msg_BankReplenishment_Handler,
		},
		{
			MethodName: "WithdrawBank",
			Handler:    _Msg_WithdrawBank_Handler,
		},
		{
			MethodName: "SpinReels",
			Handler:    _Msg_SpinReels_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trashandcashblockchain/trashandcashblockchain/tx.proto",
}

func (m *MsgBankReplenishment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBankReplenishment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBankReplenishment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgBankReplenishmentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBankReplenishmentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBankReplenishmentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgWithdrawBank) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdrawBank) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdrawBank) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgWithdrawBankResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdrawBankResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdrawBankResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSpinReels) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSpinReels) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSpinReels) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSpinReelsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSpinReelsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSpinReelsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Winning) > 0 {
		i -= len(m.Winning)
		copy(dAtA[i:], m.Winning)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Winning)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Result) > 0 {
		i -= len(m.Result)
		copy(dAtA[i:], m.Result)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Result)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Bet) > 0 {
		i -= len(m.Bet)
		copy(dAtA[i:], m.Bet)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Bet)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgBankReplenishment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgBankReplenishmentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgWithdrawBank) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgWithdrawBankResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSpinReels) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSpinReelsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	l = len(m.Bet)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Result)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Winning)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgBankReplenishment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBankReplenishment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBankReplenishment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBankReplenishmentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBankReplenishmentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBankReplenishmentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdrawBank) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdrawBank: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdrawBank: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdrawBankResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdrawBankResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdrawBankResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSpinReels) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSpinReels: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSpinReels: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSpinReelsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSpinReelsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSpinReelsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bet", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bet = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Result = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Winning", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Winning = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
